### PR TITLE
macOSX (Catalina) problems

### LINKED ISSUE #19: Qwertycoin-GUI [52522] crashing on MacOS Catalina
Crashlog below:

Process:               Qwertycoin-GUI [52522]
Path:                  /Applications/Qwertycoin-GUI.app/Contents/MacOS/Qwertycoin-GUI
Identifier:            org.qwertycoin.qwcg
Version:               5.3.1 (5.3.1)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Qwertycoin-GUI [52522]
User ID:               501

Date/Time:             2020-04-30 17:23:46.606 -0500
OS Version:            Mac OS X 10.15.4 (19E287)
Report Version:        12
Anonymous UUID:        66E7F07F-DDA7-6893-8335-A2115F46CD58

Sleep/Wake UUID:       1F143949-D973-4E09-B973-EF8F96B28B65

Time Awake Since Boot: 580000 seconds
Time Since Wake:       6400 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: /usr/local/opt/qt/lib/QtNetwork.framework/Versions/5/QtNetwork
  Referenced from: /Applications/Qwertycoin-GUI.app/Contents/MacOS/Qwertycoin-GUI
  Reason: image not found

Binary Images:
       0x10ea4f000 -        0x10eed6ffb +org.qwertycoin.qwcg (5.3.1 - 5.3.1) <A43E1616-FF16-34CD-BAF2-8034F4A2A8B0> /Applications/Qwertycoin-GUI.app/Contents/MacOS/Qwertycoin-GUI
       0x11653e000 -        0x1165cfeff  dyld (750.5) <1F893B81-89A5-3502-8510-95B97B9F730D> /usr/lib/dyld

Model: MacBookAir6,2, BootROM 120.0.0.0.0, 2 processors, Dual-Core Intel Core i7, 1.7 GHz, 8 GB, SMC 2.13f15
Graphics: kHW_IntelHD5000Item, Intel HD Graphics 5000, spdisplays_builtin
Memory Module: BANK 0/DIMM0, 4 GB, DDR3, 1600 MHz, 0x02FE, -
Memory Module: BANK 1/DIMM0, 4 GB, DDR3, 1600 MHz, 0x02FE, -
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x117), Broadcom BCM43xx 1.0 (7.77.111.1 AirPortDriverBrcmNIC-1600.4)
Bluetooth: Version 7.0.4f6, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
Serial ATA Device: APPLE SSD SD0256F, 251 GB
USB Device: USB 3.0 Bus
USB Device: BRCM20702 Hub
USB Device: Bluetooth USB Host Controller
Thunderbolt Bus: MacBook Air, Apple Inc., 23.6

### System Information

**Operating System**: 
**OS Version**: 
**CPU Make, Model, & Speed**: 
**Amount of RAM**: 
**Hard Drive Type**: 
**Hard Drive Size**: 
**Volume Type**: 

### Qwertycoin Build Information

**Version:** 
**Binary Source:** 
**If self compiled, please provide all the build commands you used**
```
Please insert your build commands here. Example:

mkdir build && cd build
cmake -DBUILD_ALL:BOOL=TRUE ..
cmake --build . --config Release
```

**If self compiled, please provide of your Qwertycoin CMake output at the default verbosity**:
```
Please insert your default verbosity CMake output here
```

### Issue Report

**Binary Reported:** 

#### Steps to Reproduce

1. 
2. 
3. 
4.

### PR DESCRIPTION
**Pull request by exploshot**
should fix #19

### CODE REVIEW

**Comment by AndreiHere** [comment]
what's the fix for Catalina? thanks

**Comment by nnian** [comment]
you will find the releases there: https://github.com/qwertycoin-org/qwertycoin-gui/releases/tag/v5.3.1.1

**Comment by AndreiHere** [comment]
unfortunately same result - it crashes right away
missing qt folder/library

**Comment by AndreiHere** [comment]
Process:               Qwertycoin-GUI [16089]
Path:                  /Applications/Qwertycoin-GUI.app/Contents/MacOS/Qwertycoin-GUI
Identifier:            org.qwertycoin.qwcg
Version:               5.3.1.1 (5.3.1.1)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Qwertycoin-GUI [16089]
User ID:               501

Date/Time:             2020-05-01 21:11:47.813 -0500
OS Version:            Mac OS X 10.15.4 (19E287)
Report Version:        12
Bridge OS Version:     3.0 (14Y908)
Anonymous UUID:        0ED63121-3146-1991-DE0A-9E9F0D8C6C5F

Sleep/Wake UUID:       32638D1D-8FC6-4829-A858-3C1396716EDE

Time Awake Since Boot: 1600000 seconds
Time Since Wake:       11000 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: /usr/local/opt/qt/lib/QtNetwork.framework/Versions/5/QtNetwork
  Referenced from: /Applications/Qwertycoin-GUI.app/Contents/MacOS/Qwertycoin-GUI
  Reason: image not found

Binary Images:
       0x10e2e4000 -        0x10e76fffb +org.qwertycoin.qwcg (5.3.1.1 - 5.3.1.1) <3366CBCB-86AA-3BA2-91E7-A8835E57B70B> /Applications/Qwertycoin-GUI.app/Contents/MacOS/Qwertycoin-GUI
       0x11a34c000 -        0x11a3ddeff  dyld (750.5) <1F893B81-89A5-3502-8510-95B97B9F730D> /usr/lib/dyld

Model: MacBookPro14,3, BootROM 205.0.0.0.0, 4 processors, Quad-Core Intel Core i7, 2.8 GHz, 16 GB, SMC 2.45f3
Graphics: kHW_AMDRadeonPro555Item, Radeon Pro 555, spdisplays_pcie_device, 2 GB
Graphics: kHW_IntelHDGraphics630Item, Intel HD Graphics 630, spdisplays_builtin
Memory Module: BANK 0/DIMM0, 8 GB, LPDDR3, 2133 MHz, 0x802C, 0x4D5435324C31473332443450472D30393320
Memory Module: BANK 1/DIMM0, 8 GB, LPDDR3, 2133 MHz, 0x802C, 0x4D5435324C31473332443450472D30393320
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x173), Broadcom BCM43xx 1.0 (7.77.111.1 AirPortDriverBrcmNIC-1600.4)
Bluetooth: Version 7.0.4f6, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB 3.0 Bus
USB Device: Apple T1 Controller
Thunderbolt Bus: MacBook Pro, Apple Inc., 41.4
Thunderbolt Bus: MacBook Pro, Apple Inc., 41.4

**Pull request merged**
